/**
 * Demo content for Explore's Nightlife and Events tabs — seeded into the
 * `nightlife_venues` and `events` tables on first boot, the same idempotent
 * way LAGOS_EXPERIENCES_SEED fills in curated trips.
 *
 * No photos: colorFallback alone renders a clean card, and it avoids
 * shipping an unverified Unsplash id that might not resolve or might not
 * actually match the place. An admin can drop a real photo on any of these
 * from /admin at any time — INSERT OR IGNORE never overwrites that edit.
 */

const NIGHTLIFE_SEED = [
  {
    id: 'night-quilox',
    name: 'Quilox',
    tagline: "Lagos's best-known club night, every weekend",
    vibe: 'Club',
    location: 'Victoria Island, Lagos',
    colorFallback: '#1A1A2E',
    feeMin: 5000,
    feeMax: 20000,
    feeNote: 'Free before 10pm, ₦5,000–₦20,000 after',
    state: 'Lagos',
    sortOrder: 0,
  },
  {
    id: 'night-cubana',
    name: 'Cubana Lounge',
    tagline: 'Cocktails, live DJs, and the VI crowd',
    vibe: 'Lounge',
    location: 'Victoria Island, Lagos',
    colorFallback: '#3D1F2B',
    feeMin: 3000,
    feeMax: 10000,
    feeNote: null,
    state: 'Lagos',
    sortOrder: 1,
  },
  {
    id: 'night-sip-rooftop',
    name: 'Sip Rooftop',
    tagline: 'Skyline views over Lekki, drink in hand',
    vibe: 'Rooftop',
    location: 'Lekki Phase 1, Lagos',
    colorFallback: '#2B3A4A',
    feeMin: 0,
    feeMax: 5000,
    feeNote: 'Free entry, drinks from ₦3,000',
    state: 'Lagos',
    sortOrder: 2,
  },
  {
    id: 'night-hard-rock',
    name: 'Hard Rock Cafe Lagos',
    tagline: 'Live bands and a full bar most nights',
    vibe: 'Live Music',
    location: 'Victoria Island, Lagos',
    colorFallback: '#4A1F1F',
    feeMin: 2000,
    feeMax: 8000,
    feeNote: null,
    state: 'Lagos',
    sortOrder: 3,
  },
  {
    id: 'night-elegushi',
    name: 'Elegushi Beach Club',
    tagline: 'Bonfire, music and the ocean right there',
    vibe: 'Beach Club',
    location: 'Elegushi Beach, Lagos',
    colorFallback: '#1F3A3A',
    feeMin: 2000,
    feeMax: 5000,
    feeNote: null,
    state: 'Lagos',
    sortOrder: 4,
  },
  {
    id: 'night-abuja-cardinal',
    name: 'Cardinal Lounge',
    tagline: "Abuja's after-dark spot for the FCT crowd",
    vibe: 'Lounge',
    location: 'Wuse II, Abuja',
    colorFallback: '#2B2B40',
    feeMin: 3000,
    feeMax: 12000,
    feeNote: null,
    state: 'Abuja',
    sortOrder: 0,
  },
  {
    id: 'night-abuja-jabi',
    name: 'Jabi Lake Rooftop',
    tagline: 'Lake views, live acts, weekend crowd',
    vibe: 'Rooftop',
    location: 'Jabi, Abuja',
    colorFallback: '#1F3550',
    feeMin: 1000,
    feeMax: 6000,
    feeNote: null,
    state: 'Abuja',
    sortOrder: 1,
  },
];

const EVENTS_SEED = [
  {
    id: 'evt-lagos-jazz',
    name: 'Lagos Jazz Series',
    tagline: 'A weekend of live jazz on the waterfront',
    description:
      'Nigerian and international jazz acts across two stages at Muri Okunola Park. Food trucks, a full bar, and one of the best-produced live music weekends in Lagos.',
    category: 'concert',
    location: 'Muri Okunola Park, Victoria Island, Lagos',
    eventDate: '2026-10-18',
    colorFallback: '#2F4A33',
    priceMin: 5000,
    priceMax: 25000,
    priceNote: null,
    ticketUrl: null,
    state: 'Lagos',
    sortOrder: 0,
  },
  {
    id: 'evt-detty-december',
    name: 'Detty December Festival',
    tagline: "Lagos's biggest end-of-year festival weekend",
    description:
      'Multiple stages, headline Afrobeats acts, and the full Detty December energy at Eko Atlantic. Bring the whole squad — this one gets busy fast.',
    category: 'festival',
    location: 'Eko Atlantic City, Lagos',
    eventDate: '2026-12-15',
    colorFallback: '#8B4513',
    priceMin: 10000,
    priceMax: 50000,
    priceNote: null,
    ticketUrl: null,
    state: 'Lagos',
    sortOrder: 1,
  },
  {
    id: 'evt-comedy-night',
    name: 'Comedy Night Live',
    tagline: 'Lagos\'s top stand-up comedians, one stage',
    description:
      'A rotating line-up of Nigeria\'s biggest comedians for one night at Terra Kulture. Doors open 7pm, show starts 8pm sharp.',
    category: 'comedy',
    location: 'Terra Kulture, Victoria Island, Lagos',
    eventDate: '2026-09-27',
    colorFallback: '#4A2F45',
    priceMin: 3000,
    priceMax: 8000,
    priceNote: null,
    ticketUrl: null,
    state: 'Lagos',
    sortOrder: 2,
  },
  {
    id: 'evt-lagos-marathon',
    name: 'Lagos City Marathon Weekend',
    tagline: 'Run it, or just come cheer the squad on',
    description:
      "Nigeria's biggest road race, with a full route through Lagos Island. Spectators line the route from National Stadium free of charge.",
    category: 'sports',
    location: 'National Stadium, Surulere, Lagos',
    eventDate: '2026-11-08',
    colorFallback: '#1E5F8E',
    priceMin: 0,
    priceMax: 0,
    priceNote: 'Free to spectate, registration required to run',
    ticketUrl: null,
    state: 'Lagos',
    sortOrder: 3,
  },
  {
    id: 'evt-abuja-carnival',
    name: 'Abuja Carnival',
    tagline: "Nigeria's capital, in full carnival colour",
    description:
      'Street parades, cultural floats and live performances through the heart of Abuja — a week-long celebration of Nigeria\'s different regions.',
    category: 'festival',
    location: 'Eagle Square, Abuja',
    eventDate: '2026-11-22',
    colorFallback: '#B0682F',
    priceMin: 0,
    priceMax: 0,
    priceNote: 'Free to attend',
    ticketUrl: null,
    state: 'Abuja',
    sortOrder: 0,
  },
];

module.exports = { NIGHTLIFE_SEED, EVENTS_SEED };
