services:
  - type: web
    name: mysquadgo-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/.puppeteer-cache
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_AUTH_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: WA_TOKEN
        sync: false
      - key: WA_PHONE_ID
        sync: false
      - key: WA_VERIFY_TOKEN
        sync: false
      - key: WA_DISPLAY_NUMBER
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: AMADEUS_CLIENT_ID
        sync: false
      - key: AMADEUS_CLIENT_SECRET
        sync: false
